name: Run the Nextstrain public builds

on:
  workflow_dispatch:
    inputs:
      dockerImage:
        description: "Specific container image to use for build (will override the default of `nextstrain build`)"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nextstrain/.github/actions/setup-nextstrain-cli@master
      - name: Launch build on AWS Batch
        run: |
          set -x

          nextstrain build \
            --aws-batch \
            --detach \
            --cpus 36 \
            --memory 72gib \
            . \
            all_public \
            -p \
            --configfile profiles/nextstrain-public.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NEXTSTRAIN_DOCKER_IMAGE: ${{ github.event.inputs.dockerImage }}
